using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConcertBooking.Entities
{
    public class Skill
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public ICollection<StudentSkill> StudentSkills { get; set; } = new List<StudentSkill>();
    }
}

// Tables will be:
// Student                 StudentSkill            Skill
// Id   Name            StudentId   SkillId        Id  Title

// Composite Key: key generated by combining 2 or more columns
// will use that to prevent redundent rows in StudentSkill table:
// e.g. StudentId   SkillId 
//      1           1
//      1           1  // should not allowed
